<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsxinc</string>
	</array>
	<key>name</key>
	<string>Syntax Name</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Includes and external syntax definition.</string>
			<key>include</key>
			<string>source.jsx</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jsxinc</string>
	<key>uuid</key>
	<string>e87f717a-2ca3-4bae-915e-9d8d681be4dd</string>
</dict>
</plist>
